### PR TITLE
Update compatibility for pom-scijava 29

### LINKED ISSUE #123: Update OMEVisual to work with the new SCIFIO
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/curtis/code/fiji-ext/OMEVisual/src/main/java/sc/fiji/omevisual/OMEUtils.java:[17,27] package io.scif.ome.formats does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

There is no SCIFIO `OMETIFFFormat` anymore. We rely on `scifio-bf-compat` for that. Probably, OMEVisual needs to grab the original format-specific `Metadata` object from the SCIFIO-opened image, and then translate it to an `OMEMetadata`, which it can display.

### PR DESCRIPTION
**Pull request by hinerm**
Closes https://github.com/scijava/pom-scijava/issues/123

### CODE REVIEW

**Comment by ctrueden** [comment]
@hadim Could you please merge this and release a new version ASAP? We need it for pom-scijava 29.0.0.

**Comment by hadim** [comment]
Done. If you want to move the repo to scijava feel free.

**Comment by ctrueden** [comment]
@hadim Thanks. Would be great to move this repo into the `fiji` org. Can you do it? We don't have admin access to this repository.

**Comment by hadim** [comment]
I just did the transfer to the fiji org.

**Comment by ctrueden** [comment]
@hadim Great! I'll cut a new release, then.

**Pull request merged**
